const SWITCHPLAYSTATE = 'SWITCHPLAYSTATE';
const SWITCHPLAYTYPE = 'SWITCHPLAYTYPE';
const UPDATETIME = 'UPDATETIME';
const UPDATEUNIT = 'UPDATEUNIT';
const SWITCHTIMER = 'SWITCHTIMER';
const MODIFYSTATISTIC = 'MODIFYSTATISTIC';

export { SWITCHPLAYSTATE, SWITCHPLAYTYPE, SWITCHTIMER, UPDATETIME, UPDATEUNIT, MODIFYSTATISTIC };