const SWITCHPLAYSTATE = 'SWITCHPLAYSTATE';
const SWITCHPLAYTYPE = 'SWITCHPLAYTYPE';
const UPDATETIME = 'UPDATETIME';
const UPDATEUNIT = 'UPDATEUNIT';
const SWITCHTIMER = 'SWITCHTIMER';
const MODIFYSTATISTIC = 'MODIFYSTATISTIC';
const ADDTIMERCARD = 'ADDTIMERCARD';
const UPDATETIMERCARD = 'UPDATETIMERCARD';
const DELETETIMERCARD = 'DELETETIMERCARD';
const INITUSERINFO = 'INITUSERINFO';
const INITPLAYINFO = 'INITPLAYINFO';
const UPDATEINTERFACESTATE = 'UPDATEINTERFACESTATE';

export { SWITCHPLAYSTATE, SWITCHPLAYTYPE, SWITCHTIMER, UPDATETIME, UPDATEUNIT, MODIFYSTATISTIC, ADDTIMERCARD, UPDATETIMERCARD, DELETETIMERCARD, INITUSERINFO, INITPLAYINFO, UPDATEINTERFACESTATE };